version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 14.17.6
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_NAME: keycloak
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      - ~/.m2:/home/keycloak/.m2

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:keycloak

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # db:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
      - ./keycloak/deployments:/opt/jboss/keycloak/standalone/deployments/
